// app/api/bookings/teacher/route.js
// POST — creates a teacher record (no login) + a booking row, then marks the
// chosen resource as "booked" so it disappears from availability counts.

import { NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { teacherBookingSchema } from '@/utils/validation';

export async function POST(request) {
  try {
    const body = await request.json();
    const parsed = teacherBookingSchema.safeParse(body);

    if (!parsed.success) {
      return NextResponse.json(
        { error: 'Invalid input', details: parsed.error.flatten() },
        { status: 400 }
      );
    }

    const { teacherName, department, email, phoneNumber, item, date, time, purpose, duration } =
      parsed.data;

    const supabase = createAdminClient();

    // 1. Create (or reuse) the teacher record
    const { data: teacher, error: teacherError } = await supabase
      .from('teachers')
      .insert({
        full_name: teacherName,
        department,
        email,
        phone_number: phoneNumber,
      })
      .select()
      .single();

    if (teacherError) throw teacherError;

    // 2. Find an available resource of the requested type
    const { data: resource, error: resourceError } = await supabase
      .from('resources')
      .select('*')
      .eq('resource_type', item)
      .eq('status', 'available')
      .limit(1)
      .maybeSingle();

    if (resourceError) throw resourceError;

    if (!resource) {
      return NextResponse.json(
        { error: `No ${item === 'projector' ? 'projectors' : 'computer laboratories'} are currently available.` },
        { status: 409 }
      );
    }

    // 3. Create the booking (booking_number is auto-generated by a DB trigger)
    const { data: booking, error: bookingError } = await supabase
      .from('bookings')
      .insert({
        booking_type: 'teacher',
        teacher_id: teacher.id,
        resource_id: resource.id,
        resource_type: item,
        booking_date: date,
        booking_time: time,
        purpose,
        duration,
        status: 'approved', // Teacher bookings for a single projector/lab don't need the club approval chain
      })
      .select()
      .single();

    if (bookingError) throw bookingError;

    // 4. Mark the resource as booked and record who holds it
    const { error: updateError } = await supabase
      .from('resources')
      .update({
        status: 'booked',
        current_holder: teacherName,
        issue_date: date,
      })
      .eq('id', resource.id);

    if (updateError) throw updateError;

    // 5. Log it in the inventory trail
    await supabase.from('inventory_logs').insert({
      resource_id: resource.id,
      booking_id: booking.id,
      action: 'issued',
      notes: `Issued to ${teacherName} (${department}) via teacher booking form.`,
    });

    return NextResponse.json({ booking, resource }, { status: 201 });
  } catch (error) {
    console.error('Teacher booking error:', error);
    return NextResponse.json({ error: 'Something went wrong creating the booking.' }, { status: 500 });
  }
}
